#!/usr/bin/env node
/**
 * Security Alert Email — Data Toyz Terminal
 *
 * Sends a red-flag email via Resend when the security audit detects failures.
 * Reads the report from security-report.json (generated by security-audit.js).
 *
 * Required env vars:
 *   RESEND_API_KEY       — Resend API key (already in your Render env)
 *   SECURITY_ALERT_EMAIL — Recipient email for alerts (defaults to jwsounds@gmail.com)
 *   RESEND_FROM_EMAIL    — Sender address (optional, defaults to onboarding@resend.dev)
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const REPORT_PATH = path.join(ROOT, 'security-report.json');

async function sendAlert() {
    // 1. Read the report
    if (!fs.existsSync(REPORT_PATH)) {
        console.log('No security-report.json found — run npm run security-check first.');
        process.exit(1);
    }

    const report = JSON.parse(fs.readFileSync(REPORT_PATH, 'utf8'));

    // 2. Only send if there are failures or warnings
    if (report.failed === 0 && report.warnings === 0) {
        console.log('All clear — no alert email needed.');
        return;
    }

    // 3. Check required env vars
    const RESEND_API_KEY = process.env.RESEND_API_KEY;
    const ALERT_EMAIL = process.env.SECURITY_ALERT_EMAIL || 'jwsounds@gmail.com';
    const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || 'Data Toyz Terminal <onboarding@resend.dev>';

    if (!RESEND_API_KEY) {
        console.error('RESEND_API_KEY not set — cannot send alert email.');
        process.exit(1);
    }

    // 4. Build the email
    const severity = report.failed > 0 ? 'CRITICAL' : 'WARNING';
    const emoji = report.failed > 0 ? '\u{1F6A8}' : '\u{26A0}\u{FE0F}';

    const failureList = report.failureDetails.length > 0
        ? report.failureDetails.map(f => `<li style="color:#dc2626;margin-bottom:8px;">${f}</li>`).join('\n')
        : '';

    const warningList = report.warningDetails.length > 0
        ? report.warningDetails.map(w => `<li style="color:#d97706;margin-bottom:8px;">${w}</li>`).join('\n')
        : '';

    const html = `
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:600px;margin:0 auto;">
        <div style="background:${report.failed > 0 ? '#dc2626' : '#d97706'};color:white;padding:20px 24px;border-radius:8px 8px 0 0;">
            <h1 style="margin:0;font-size:22px;">${emoji} Security Alert — ${severity}</h1>
            <p style="margin:8px 0 0;opacity:0.9;font-size:14px;">Data Toyz Terminal • ${new Date(report.timestamp).toLocaleString()}</p>
        </div>

        <div style="background:#1a1a2e;color:#e0e0e0;padding:24px;border-radius:0 0 8px 8px;">
            <div style="display:flex;gap:24px;margin-bottom:20px;">
                <div style="text-align:center;">
                    <div style="font-size:28px;font-weight:bold;color:#22c55e;">${report.passed}</div>
                    <div style="font-size:12px;color:#888;">Passed</div>
                </div>
                <div style="text-align:center;">
                    <div style="font-size:28px;font-weight:bold;color:#d97706;">${report.warnings}</div>
                    <div style="font-size:12px;color:#888;">Warnings</div>
                </div>
                <div style="text-align:center;">
                    <div style="font-size:28px;font-weight:bold;color:#dc2626;">${report.failed}</div>
                    <div style="font-size:12px;color:#888;">Failed</div>
                </div>
            </div>

            ${report.failureDetails.length > 0 ? `
            <h3 style="color:#dc2626;margin:16px 0 8px;border-bottom:1px solid #333;padding-bottom:8px;">Failed Checks</h3>
            <ul style="padding-left:20px;line-height:1.6;">${failureList}</ul>
            ` : ''}

            ${report.warningDetails.length > 0 ? `
            <h3 style="color:#d97706;margin:16px 0 8px;border-bottom:1px solid #333;padding-bottom:8px;">Warnings</h3>
            <ul style="padding-left:20px;line-height:1.6;">${warningList}</ul>
            ` : ''}

            <p style="margin-top:24px;padding-top:16px;border-top:1px solid #333;font-size:13px;color:#888;">
                Run <code style="background:#333;padding:2px 6px;border-radius:4px;">npm run security-check</code> locally for full details.
            </p>
        </div>
    </div>`;

    // 5. Send via Resend
    const { Resend } = require('resend');
    const resend = new Resend(RESEND_API_KEY);

    try {
        const result = await resend.emails.send({
            from: FROM_EMAIL,
            to: ALERT_EMAIL,
            subject: `${emoji} [${severity}] Security Scan — ${report.failed} failed, ${report.warnings} warnings`,
            html: html
        });

        console.log(`Alert email sent to ${ALERT_EMAIL} (id: ${result.data?.id || 'sent'})`);
    } catch (err) {
        console.error('Failed to send alert email:', err.message);
        process.exit(1);
    }
}

sendAlert();
